config/routes.rb
Icap::Application.routes.draw do
  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'pages#signin'
  match '/signup', :to => 'users#new'
  get "pages/home"
  get "pages/contact"
  get "pages/help"
  get "users/new"

  
  
  resources :phones

  resources :calllogs

  resources :incentives

  resources :narratives

  resources :ptids

   root :to => "pages#home", :as => 'home'

end

app/models/incentive.rb
class Incentive < ActiveRecord::Base
validates_length_of :ptid, is => 10
  validates_numericality_of :ptid
  validates_uniqueness_of :ptid
  validates_presence_of :ptid
has_one :ptid

end

app/controllers/incentives_controller.rb
class IncentivesController < ApplicationController
  # GET /incentives
  # GET /incentives.xml
  def index
    @incentives = Incentive.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @incentives }
    end
  end

  # GET /incentives/1
  # GET /incentives/1.xml
  def show
    @incentive = Incentive.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @incentive }
    end
  end

  # GET /incentives/new
  # GET /incentives/new.xml
  def new
    @incentive = Incentive.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @incentive }
    end
  end

  # GET /incentives/1/edit
  def edit
    @incentive = Incentive.find(params[:id])
  end

  # POST /incentives
  # POST /incentives.xml
  def create
    @incentive = Incentive.new(params[:incentive])

    respond_to do |format|
      if @incentive.save
        format.html { redirect_to(@incentive, :notice => 'Incentive was successfully created.') }
        format.xml  { render :xml => @incentive, :status => :created, :location => @incentive }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @incentive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /incentives/1
  # PUT /incentives/1.xml
  def update
    @incentive = Incentive.find(params[:id])

    respond_to do |format|
      if @incentive.update_attributes(params[:incentive])
        format.html { redirect_to(@incentive, :notice => 'Incentive was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @incentive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /incentives/1
  # DELETE /incentives/1.xml
  def destroy
    @incentive = Incentive.find(params[:id])
    @incentive.destroy

    respond_to do |format|
      format.html { redirect_to(incentives_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/incentives_helper.rb
module IncentivesHelper
end

app/views/incentives/_form.html.erb
<%= form_for(@incentive) do |f| %>
  <% if @incentive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incentive.errors.count, "error") %> prohibited this incentive from being saved:</h2>

      <ul>
      <% @incentive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ptid %><br />
    <%= f.text_field :ptid %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br />
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :date_out %><br />
    <%= f.date_select :date_out %>
  </div>
  <div class="field">
    <%= f.label :field_manager %><br />
    <%= f.text_field :field_manager %>
  </div>
  <div class="field">
    <%= f.label :transfered %><br />
    <%= f.check_box :transfered %>
  </div>
  <div class="field">
    <%= f.label :date_transfered %><br />
    <%= f.date_select :date_transfered %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incentives/edit.html.erb
<h1>Editing incentive</h1>

<%= render 'form' %>

<%= link_to 'Show', @incentive %> |
<%= link_to 'Back', incentives_path %>

app/views/incentives/index.html.erb
<h1>Listing incentives</h1>

<table>
  <tr>
    <th>Ptid</th>
    <th>Serial number</th>
    <th>Date out</th>
    <th>Field manager</th>
    <th>Transfered</th>
    <th>Date transfered</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @incentives.each do |incentive| %>
  <tr>
    <td><%= incentive.ptid %></td>
    <td><%= incentive.serial_number %></td>
    <td><%= incentive.date_out %></td>
    <td><%= incentive.field_manager %></td>
    <td><%= incentive.transfered %></td>
    <td><%= incentive.date_transfered %></td>
    <td><%= link_to 'Show', incentive %></td>
    <td><%= link_to 'Edit', edit_incentive_path(incentive) %></td>
    <td><%= link_to 'Destroy', incentive, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Incentive', new_incentive_path %>

app/views/incentives/new.html.erb
<h1>New incentive</h1>

<%= render 'form' %>

<%= link_to 'Back', incentives_path %>

app/views/incentives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ptid:</b>
  <%= @incentive.ptid %>
</p>

<p>
  <b>Serial number:</b>
  <%= @incentive.serial_number %>
</p>

<p>
  <b>Date out:</b>
  <%= @incentive.date_out %>
</p>

<p>
  <b>Field manager:</b>
  <%= @incentive.field_manager %>
</p>

<p>
  <b>Transfered:</b>
  <%= @incentive.transfered %>
</p>

<p>
  <b>Date transfered:</b>
  <%= @incentive.date_transfered %>
</p>


<%= link_to 'Edit', edit_incentive_path(@incentive) %> |
<%= link_to 'Back', incentives_path %>