config/routes.rb
Icap::Application.routes.draw do
  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'pages#signin'
  match '/signup', :to => 'users#new'
  get "pages/home"
  get "pages/contact"
  get "pages/help"
  get "users/new"

  
  
  resources :phones

  resources :calllogs

  resources :incentives

  resources :narratives

  resources :ptids

   root :to => "pages#home", :as => 'home'

end

app/models/ptid.rb
class Ptid < ActiveRecord::Base
  set_primary_key :ptid
  
  validates_length_of :ptid, :is => 10
  validates_numericality_of :ptid
  validates_uniqueness_of :ptid
  validates_presence_of :ptid
  
  has_many :phones
  has_many :narratives
  has_one :incentives
  
end

app/controllers/ptids_controller.rb
class PtidsController < ApplicationController
  # GET /ptids
  # GET /ptids.xml
  def index
    @ptids = Ptid.all
    @title = "Reviewing PTIDs'"
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ptids }
    end
  end

  # GET /ptids/1
  # GET /ptids/1.xml
  def show
    @ptid = Ptid.find(params[:id])
    @title = Ptid.find(params[:id]).ptid + " Details"
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ptid }
    end
  end

  # GET /ptids/new
  # GET /ptids/new.xml
  def new
    @ptid = Ptid.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ptid }
    end
  end

  # GET /ptids/1/edit
  def edit
    @ptid = Ptid.find(params[:id])
  end

  # POST /ptids
  # POST /ptids.xml
  def create
    @ptid = Ptid.new(params[:ptid])

    respond_to do |format|
      if @ptid.save
        format.html { redirect_to(@ptid, :notice => 'Ptid was successfully created.') }
        format.xml  { render :xml => @ptid, :status => :created, :location => @ptid }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ptid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ptids/1
  # PUT /ptids/1.xml
  def update
    @ptid = Ptid.find(params[:id])

    respond_to do |format|
      if @ptid.update_attributes(params[:ptid])
        format.html { redirect_to(@ptid, :notice => 'Ptid was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ptid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ptids/1
  # DELETE /ptids/1.xml
  def destroy
    @ptid = Ptid.find(params[:id])
    @ptid.destroy

    respond_to do |format|
      format.html { redirect_to(ptids_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ptids_helper.rb
module PtidsHelper
end

app/views/ptids/_form.html.erb
<%= form_for(@ptid) do |f| %>
  <% if @ptid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ptid.errors.count, "error") %> prohibited this ptid from being saved:</h2>

      <ul>
      <% @ptid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ptid %><br />
    <%= f.text_field :ptid %>
  </div>
  <div class="field">
    <%= f.label :enrollment %><br />
    <%= f.date_select :enrollment %>
  </div>
  <div class="field">
    <%= f.label :follow_up %><br />
    <%= f.date_select :follow_up %>
  </div>
  <div class="field">
    <%= f.label :handover %><br />
    <%= f.date_select :handover %>
  </div>
  <div class="field">
    <%= f.label :completion_code %><br />
    <%= f.text_field :completion_code %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ptids/edit.html.erb
<h1>Editing ptid</h1>

<%= render 'form' %>

<%= link_to 'Show', @ptid %> |
<%= link_to 'Back', ptids_path %>

app/views/ptids/index.html.erb
<h1>Listing ptids</h1>

<table>
  <tr>
    <th>Ptid</th>
    <th>Enrollment</th>
    <th>Follow up</th>
    <th>Handover</th>
    <th>Completion code</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ptids.each do |ptid| %>
  <tr class="<%= cycle('list_line_odd', 'List_line_even') %>">
    <td><%= ptid.ptid %></td>
    <td><%= ptid.enrollment %></td>
    <td><%= ptid.follow_up %></td>
    <td><%= ptid.handover %></td>
    <td><%= ptid.completion_code %></td>
    <td><%= ptid.user_id %></td>
    <td><%= link_to 'Show', ptid %></td>
    <td><%= link_to 'Edit', edit_ptid_path(ptid) %></td>
    <td><%= link_to 'Destroy', ptid, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ptid', new_ptid_path %>

app/views/ptids/new.html.erb
<h1>New ptid</h1>

<%= render 'form' %>

<%= link_to 'Back', ptids_path %>

app/views/ptids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ptid:</b>
  <%= @ptid.ptid %>
</p>

<p>
  <b>Enrollment:</b>
  <%= @ptid.enrollment %>
</p>

<p>
  <b>Follow up:</b>
  <%= @ptid.follow_up %>
</p>

<p>
  <b>Handover:</b>
  <%= @ptid.handover %>
</p>

<p>
  <b>Completion code:</b>
  <%= @ptid.completion_code %>
</p>

<p>
  <b>User:</b>
  <%= @ptid.user_id %>
</p>


<%= link_to 'Edit', edit_ptid_path(@ptid) %> |
<%= link_to 'Back', ptids_path %>