config/routes.rb
Icap::Application.routes.draw do
  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'pages#signin'
  match '/signup', :to => 'users#new'
  get "pages/home"
  get "pages/contact"
  get "pages/help"
  get "users/new"

  
  
  resources :phones

  resources :calllogs

  resources :incentives

  resources :narratives

  resources :ptids

   root :to => "pages#home", :as => 'home'

end

app/models/narrative.rb
class Narrative < ActiveRecord::Base
  validates_length_of :ptid, is => 10
  validates_numericality_of :ptid
  validates_presence_of :ptid
end

app/controllers/narratives_controller.rb
class NarrativesController < ApplicationController
  # GET /narratives
  # GET /narratives.xml
  def index
    @narratives = Narrative.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @narratives }
    end
  end

  # GET /narratives/1
  # GET /narratives/1.xml
  def show
    @narrative = Narrative.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @narrative }
    end
  end

  # GET /narratives/new
  # GET /narratives/new.xml
  def new
    @narrative = Narrative.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @narrative }
    end
  end

  # GET /narratives/1/edit
  def edit
    @narrative = Narrative.find(params[:id])
  end

  # POST /narratives
  # POST /narratives.xml
  def create
    @narrative = Narrative.new(params[:narrative])

    respond_to do |format|
      if @narrative.save
        format.html { redirect_to(@narrative, :notice => 'Narrative was successfully created.') }
        format.xml  { render :xml => @narrative, :status => :created, :location => @narrative }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @narrative.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /narratives/1
  # PUT /narratives/1.xml
  def update
    @narrative = Narrative.find(params[:id])

    respond_to do |format|
      if @narrative.update_attributes(params[:narrative])
        format.html { redirect_to(@narrative, :notice => 'Narrative was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @narrative.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /narratives/1
  # DELETE /narratives/1.xml
  def destroy
    @narrative = Narrative.find(params[:id])
    @narrative.destroy

    respond_to do |format|
      format.html { redirect_to(narratives_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/narratives_helper.rb
module NarrativesHelper
end

app/views/narratives/_form.html.erb
<%= form_for(@narrative) do |f| %>
  <% if @narrative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@narrative.errors.count, "error") %> prohibited this narrative from being saved:</h2>

      <ul>
      <% @narrative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ptid %><br />
    <%= f.text_field :ptid %>
  </div>
  <div class="field">
    <%= f.label :narratte %><br />
    <%= f.text_area :narratte %>
  </div>
  <div class="field">
    <%= f.label :review %><br />
    <%= f.check_box :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/narratives/edit.html.erb
<h1>Editing narrative</h1>

<%= render 'form' %>

<%= link_to 'Show', @narrative %> |
<%= link_to 'Back', narratives_path %>

app/views/narratives/index.html.erb
<h1>Listing narratives</h1>

<table>
  <tr>
    <th>Ptid</th>
    <th>Narratte</th>
    <th>Review</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @narratives.each do |narrative| %>
  <tr>
    <td><%= narrative.ptid %></td>
    <td><%= narrative.narratte %></td>
    <td><%= narrative.review %></td>
    <td><%= link_to 'Show', narrative %></td>
    <td><%= link_to 'Edit', edit_narrative_path(narrative) %></td>
    <td><%= link_to 'Destroy', narrative, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Narrative', new_narrative_path %>

app/views/narratives/new.html.erb
<h1>New narrative</h1>

<%= render 'form' %>

<%= link_to 'Back', narratives_path %>

app/views/narratives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ptid:</b>
  <%= @narrative.ptid %>
</p>

<p>
  <b>Narratte:</b>
  <%= @narrative.narratte %>
</p>

<p>
  <b>Review:</b>
  <%= @narrative.review %>
</p>


<%= link_to 'Edit', edit_narrative_path(@narrative) %> |
<%= link_to 'Back', narratives_path %>