config/routes.rb
Icap::Application.routes.draw do
  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'pages#signin'
  match '/signup', :to => 'users#new'
  get "pages/home"
  get "pages/contact"
  get "pages/help"
  get "users/new"

  
  
  resources :phones

  resources :calllogs

  resources :incentives

  resources :narratives

  resources :ptids

   root :to => "pages#home", :as => 'home'

end

app/models/calllog.rb
class Calllog < ActiveRecord::Base
  validates_length_of :ptid, :is => 10
  validates_numericality_of :ptid

  validates_presence_of :ptid
  has_many :narratives 
  belongs_to :phones
end

app/controllers/calllogs_controller.rb
class CalllogsController < ApplicationController
  # GET /calllogs
  # GET /calllogs.xml
  def index
    @calllogs = Calllog.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @calllogs }
    end
  end

  # GET /calllogs/1
  # GET /calllogs/1.xml
  def show
    @calllog = Calllog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @calllog }
    end
  end

  # GET /calllogs/new
  # GET /calllogs/new.xml
  def new
    @calllog = Calllog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @calllog }
    end
  end

  # GET /calllogs/1/edit
  def edit
    @calllog = Calllog.find(params[:id])
  end

  # POST /calllogs
  # POST /calllogs.xml
  def create
    @calllog = Calllog.new(params[:calllog])

    respond_to do |format|
      if @calllog.save
        format.html { redirect_to(@calllog, :notice => 'Calllog was successfully created.') }
        format.xml  { render :xml => @calllog, :status => :created, :location => @calllog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @calllog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /calllogs/1
  # PUT /calllogs/1.xml
  def update
    @calllog = Calllog.find(params[:id])

    respond_to do |format|
      if @calllog.update_attributes(params[:calllog])
        format.html { redirect_to(@calllog, :notice => 'Calllog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @calllog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /calllogs/1
  # DELETE /calllogs/1.xml
  def destroy
    @calllog = Calllog.find(params[:id])
    @calllog.destroy

    respond_to do |format|
      format.html { redirect_to(calllogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/calllogs_helper.rb
module CalllogsHelper
end

app/views/calllogs/_form.html.erb
<%= form_for(@calllog) do |f| %>
  <% if @calllog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calllog.errors.count, "error") %> prohibited this calllog from being saved:</h2>

      <ul>
      <% @calllog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ptid %><br />
    <%= f.text_field :ptid %>
  </div>
  <div class="field">
    <%= f.label :number_id %><br />
    <%= f.text_field :number_id %>
  </div>
  <div class="field">
    <%= f.label :attempttime %><br />
    <%= f.time_select :attempttime %>
  </div>
  <div class="field">
    <%= f.label :outcome %><br />
    <%= f.text_field :outcome %>
  </div>
  <div class="field">
    <%= f.label :answerer %><br />
    <%= f.text_field :answerer %>
  </div>
  <div class="field">
    <%= f.label :refferal_number %><br />
    <%= f.text_field :refferal_number %>
  </div>
  <div class="field">
    <%= f.label :callback %><br />
    <%= f.time_select :callback %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calllogs/edit.html.erb
<h1>Editing calllog</h1>

<%= render 'form' %>

<%= link_to 'Show', @calllog %> |
<%= link_to 'Back', calllogs_path %>

app/views/calllogs/index.html.erb
<h1>Listing calllogs</h1>

<table>
  <tr>
    <th>Ptid</th>
    <th>Number</th>
    <th>Attempttime</th>
    <th>Outcome</th>
    <th>Answerer</th>
    <th>Refferal number</th>
    <th>Callback</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calllogs.each do |calllog| %>
  <tr>
    <td><%= calllog.ptid %></td>
    <td><%= calllog.number_id %></td>
    <td><%= calllog.attempttime %></td>
    <td><%= calllog.outcome %></td>
    <td><%= calllog.answerer %></td>
    <td><%= calllog.refferal_number %></td>
    <td><%= calllog.callback %></td>
    <td><%= calllog.comments %></td>
    <td><%= link_to 'Show', calllog %></td>
    <td><%= link_to 'Edit', edit_calllog_path(calllog) %></td>
    <td><%= link_to 'Destroy', calllog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Calllog', new_calllog_path %>

app/views/calllogs/new.html.erb
<h1>New calllog</h1>

<%= render 'form' %>

<%= link_to 'Back', calllogs_path %>

app/views/calllogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ptid:</b>
  <%= @calllog.ptid %>
</p>

<p>
  <b>Number:</b>
  <%= @calllog.number_id %>
</p>

<p>
  <b>Attempttime:</b>
  <%= @calllog.attempttime %>
</p>

<p>
  <b>Outcome:</b>
  <%= @calllog.outcome %>
</p>

<p>
  <b>Answerer:</b>
  <%= @calllog.answerer %>
</p>

<p>
  <b>Refferal number:</b>
  <%= @calllog.refferal_number %>
</p>

<p>
  <b>Callback:</b>
  <%= @calllog.callback %>
</p>

<p>
  <b>Comments:</b>
  <%= @calllog.comments %>
</p>


<%= link_to 'Edit', edit_calllog_path(@calllog) %> |
<%= link_to 'Back', calllogs_path %>